# example values
server:
  port: 8080

spring:
  datasource:
    username: root
    password: Tasha0406!
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default-character-set: utf8mb4
    hibernate:
      ddl-auto: create
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://radiomv.ru
      name: RadioMv.Ru
